CREATE OR REPLACE PROCEDURE PROC_CURSOR_TEST
IS
  CURSOR CGYOMU IS
  SELECT COL1 FROM TEST_1;
  CRGYOMU CGYOMU%ROWTYPE;
  n number:=1;
BEGIN
  OPEN CGYOMU;
  LOOP
    FETCH CGYOMU INTO CRGYOMU;
    EXIT WHEN CGYOMU%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(n || 'gyo');
    n := n + 1;
    IF CRGYOMU.COL1 = 2 THEN
      -- CLOSE CGYOMU;
      DBMS_OUTPUT.PUT_LINE('WITHOUT CURSOR CLOSING 1');
      RETURN;
    END IF;
  END LOOP;
  -- CLOSE CGYOMU;
  DBMS_OUTPUT.PUT_LINE('WITHOUT CURSOR CLOSING 2');
  EXCEPTION
  WHEN OTHERS THEN
    IF CGYOMU%ISOPEN THEN
      DBMS_OUTPUT.PUT_LINE('WITHOUT CURSOR CLOSING 3');
      --CLOSE CGYOMU;        
    END IF;                
END PROC_CURSOR_TEST;
/
