CREATE OR REPLACE PROCEDURE PROC_COMPARE_TEST
IS

  C_1 CHAR(6):='202011';
  C_2 CHAR(6):='202012';
  CV_1 VARCHAR2(6):='202011';
  CV_2 VARCHAR2(6):='202012';
  D_1 DATE:=SYSDATE-1;
  D_2 DATE:=SYSDATE;
  N_1 NUMBER:=202011;
  N_2 NUMBER:=202012;
BEGIN
  
  DBMS_OUTPUT.PUT_LINE('C_1 = ' || C_1);
  DBMS_OUTPUT.PUT_LINE('C_2 = ' || C_2);
  DBMS_OUTPUT.PUT_LINE('CV_1 = ' || CV_1);
  DBMS_OUTPUT.PUT_LINE('CV_2 = ' || CV_2);
  DBMS_OUTPUT.PUT_LINE('D_1 = ' || D_1);
  DBMS_OUTPUT.PUT_LINE('D_2 = ' || D_2);
  DBMS_OUTPUT.PUT_LINE('N_1 = ' || N_1);
  DBMS_OUTPUT.PUT_LINE('N_2 = ' || N_2);

  IF C_1 < C_2 THEN
     DBMS_OUTPUT.PUT_LINE('C_1 < C_2  CHAR COMPARE');
  END IF;
  
  IF CV_1 < CV_2 THEN
     DBMS_OUTPUT.PUT_LINE('CV_1 < CV_2 VARCHAR2 COMPARE');
  END IF;

  IF D_1 < D_2 THEN
     DBMS_OUTPUT.PUT_LINE('D_1 < D_2 DATE COMPARE');
  END IF;
  
  IF N_1 < N_2 THEN
     DBMS_OUTPUT.PUT_LINE('N_1 < N_2 NUMBER COMPARE');
  END IF;
  
END PROC_COMPARE_TEST;
/
