CREATE OR REPLACE PROCEDURE PROC_NOTUSE_TEST
IS
  CURSOR CGYOMU IS
  SELECT COL1 FROM TEST_1;
  CRGYOMU CGYOMU%ROWTYPE;
  n number:=1;
BEGIN
  DBMS_OUTPUT.PUT_LINE('NOT USE TEST');
END PROC_NOTUSE_TEST;
/
